### ISSUE TITLE
property[0] = user's content (untrusted)

### ISSUE THREAD

**Issue by yuriy77k** [Dexaran/CallistoNFT#5]
According to code:
https://github.com/Dexaran/CallistoNFT/blob/a886f3bb0321c5100fd193ee94363bc60d625b5d/ERC721Compatible/ERC721CallistoNFTHybrid.sol#L619-L629

the `property[0]` is user content the token owner can change as he likes. We have to say about it in the standard description that  `property[0]`  is untrusted info.
Without a clear description, users may easily scam buyers by putting in  `property[0]` info from other tokens (probably more expensive) and selling their tokens by overpricing.

Since we have no strictly standard for which property represents real (unchangeable) info we could not identify where located real info about Art is represented by NFT and where is user specified info.

**Comment by Dexaran** [comment]
NFT token identifier is it's contract address. Contract address is persistent and immutable.

If you are trying to assess which token you are looking at by reviewing the content of `properties` then it is just a wrong approach.

Similarly, you don't recognize ERC20 token by looking at it's "Symbol" or "Name" value because anyone can deploy a new contract and give it name "USDT" or "Tether" and mint tokens as he wants. It doesn't make his token into real USDT however. What really defines which token is USDT and which is not real USDT is contract address.
